### ISSUE TITLE
After latest release we have blocker issue

### ISSUE THREAD

**Issue by cristiboariu** [opentracing/opentracing-javascript#172]
After your latest release (v0.14.6) we encounter:

```
Error encountered when starting the app: TypeError: Cannot use 'in' operator to search for 'context' in null
/opt/app/node_modules/opentracing/lib/reference.js:14
    if (contextOrSpan instanceof span_1.default || 'context' in contextOrSpan) {
                                                             ^

TypeError: Cannot use 'in' operator to search for 'context' in null
    at toContext (/opt/app/node_modules/opentracing/lib/reference.js:14:62)
    at new Reference (/opt/app/node_modules/opentracing/lib/reference.js:37:35)
    at Object.requestTrace [as request] (/opt/app/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:57:11)
    at retriableRequest (/opt/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/request.js:13:22)
    at request (/opt/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/request.js:53:24)
    at makeRequest (/opt/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:127:3)
    at Writer._sendPayload (/opt/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:31:5)
    at Writer.flush (/opt/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:80:12)
    at Timeout._onTimeout (/opt/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/index.js:14:58)
```

**Comment by cristiboariu** [comment]
@yurishkuro can you please help? Our PROD build are no longer working :(

**Comment by lmuench** [comment]
we are experiencing the same issue

**Comment by jneal-afs** [comment]
Seeing this as well

**Comment by jneal-afs** [comment]
@yurishkuro Just want to make sure you are aware. We are currently trying to force a rollback to v0.14.5 in our systems as we currently can't deploy any new code.

**Comment by amopportunities** [comment]
dd-trace datadogs agent uses this and we can not deploy any code now. this is a major issue.

**Comment by yurishkuro** [comment]
apologies, everyone, I am reverting the change in a new patch

**Comment by yurishkuro** [comment]
opentracing@0.14.7 published that is equal to opentracing@0.14.5

**Comment by yurishkuro** [comment]
btw, I think the original null-ptr issue is here: https://github.com/DataDog/dd-trace-js/blob/21179be27f7f9487e8287056fa08e404f5e6ef14/packages/datadog-plugin-http/src/client.js#L54

This code is calling `new Reference(type, parentCtx)` constructor with `parentCtx=null`, which is invalid per constructor signature: https://github.com/opentracing/opentracing-javascript/blob/9a4856ef20597c1a1a2ffc4072dd9a497af22b8d/src/reference.ts#L57

**Comment by yurishkuro** [comment]
While not ideal, #174 adds support for previous "illegal" usage of the constructor.

**Comment by dhay** [comment]
I was facing this issue as well and can confirm that the 0.14.7 build fixes the problem.  I was about to post this exact issue with the suggestion that the line in question add a null/undefined check...but, without digging further, that may just kick the problem further downstream

**Comment by yurishkuro** [comment]
@cristiboariu @lmuench @jneal-afs @amopportunities @dhay can you test your code with PR #174 (it's on a public branch) to confirm if it resolves the issue?
